
name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      # Runs a single command using the runners shell
  build:
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/buildNugetPackage.yml@main
  GenerateDocs:
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/GenerateDocs.yml@main
