name: Build documentation

on:
  workflow_call:

env:
    # Name of module and id separated by a slash
    INSTANCE: Writerside/adoc
    # Replace HI with the ID of the instance in capital letters
    ARTIFACT: webHelpHI2-all.zip
    # Writerside docker image version
    DOCKER_VERSION: 232.10275

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x
            - name: Restore
              run: dotnet restore
              working-directory: src
            - name: Build
              run: dotnet build --no-restore
              working-directory: src
        
            - name: Test
              run: dotnet test
              working-directory: src
            
            - name: Generate Schema
              run: dotnet run --project ./SchemaGenerator/SchemaGenerator.csproj
              working-directory: src

            - name: Build Writerside docs using Docker
              uses: JetBrains/writerside-github-action@v4
              with:
                instance: ${{ env.INSTANCE }}
                artifact: ${{ env.ARTIFACT }}
                docker-version: ${{ env.DOCKER_VERSION }}

            - name: Upload documentation
              uses: actions/upload-artifact@v3
              with:
                name: docs
                path: |
                    artifacts/${{ env.ARTIFACT }}
                    artifacts/report.json
                retention-days: 7


# Add the job below and artifacts/report.json on Upload documentation step above if you want to fail the build when documentation contains errors
    test:
    # Requires build job results
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v1
              with:
                name: docs
                path: artifacts

            - name: Test documentation
              uses: JetBrains/writerside-checker-action@v1
              with:
                instance: ${{ env.INSTANCE }}
