# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish
on:
  workflow_call:
    secrets:
      NUGET_APIKEY:
        required: true
env:
  NuGetDirectory: ${{ github.workspace}}/nuget
jobs:
  Publish:
    
    if:  github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v4
        with:
          name: Nuget Build Output
          path: ${{ env.NuGetDirectory }}
  
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
  
      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet package
        run: |
          dotnet nuget push "**/*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
